### PR TITLE
Custom anchors for bibliographies and citations.

### PR DESCRIPTION
**Pull request by mcmtroffaes**
See issue #264. Still WIP for now.

### CODE REVIEW

**Comment by mcmtroffaes** [comment]
@mforbes Would you mind testing out this feature branch? You should get custom citation html anchors by adding the following to your ``conf.py``:

```python
bibtex_cite_id = "cite-{key}"
```

You can customize the prefix by editing the template string. If you have multiple bibliography directives in any single document, this will do:

```python
bibtex_cite_id = "cite-{bibliography_count}-{key}"
```

**Comment by kmuehlbauer** [comment]
@mcmtroffaes I'll get to this. Will report back tomorrow latest.

**Comment by kmuehlbauer** [comment]
@mcmtroffaes That works very well on my side. Thanks again for taking care!

**Comment by mcmtroffaes** [comment]
Awesome, thanks for reporting and helping to test!

**Pull request merged**
