### PR TITLE
Improve citation ordering code (see issue #15 and issue #182).

### PR DESCRIPTION
**Pull request by mcmtroffaes**

### CODE REVIEW

**Comment by mcmtroffaes** [comment]
@ukos-git Could you test and check that this pull request fixes your problem?

One issue I still see is that it's not clear to me that the full toctree will be built when the transform kicks in, however, this may be the best we can do. I'd be happier to compute the ordering across all documents outside the transform, ideally when the full toctree is built (i.e. when all documents are already processed). But I can't see a simple way of doing that with Sphinx's API.

**Comment by ukos-git** [comment]
Thank you for taking the effort. That solution works fine here. I will do some more testing the next 2 days and report back.

**Comment by mcmtroffaes** [comment]
Ok, thanks, that's appreciated!

**Comment by ukos-git** [comment]
The following sphinx error message seems related. It is not fatal, though.

```
[html:25] parsing bibtex file /drone/src/citation/citation.bib... parsed 570 entries
[html:26] ERROR:  'IterableList' object has no attribute 'origin'
```

**Pull request merged**
