### PR TITLE
Migrate to pyproject.

### LINKED ISSUE #350: setup.py: migrate deprecated namespace_packages
Please consider changing to native namespace packages.

https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages

### PR DESCRIPTION
**Pull request by mcmtroffaes**
This fixes #350 (and removes setuptools as a dependency for installation).

### CODE REVIEW

**Comment by danielnorberg** [comment]
Nice!👍

**Comment by mcmtroffaes** [comment]
Is it necessary (there are no build dependencies)?

**Comment by mcmtroffaes** [comment]
Aw poop, yes it i, from https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

```
The [build-system] table should always be present, regardless of which build backend you use ([build-system] defines the build tool you use).
```

I'll add one now.

**Comment by mcmtroffaes** [comment]
Added here: https://github.com/mcmtroffaes/sphinxcontrib-bibtex/commit/9ca4e0beacd55075108111ec84039ac82992adb1

**Comment by flying-sheep** [comment]
Awesome! Yeah, there is a build dependency: `setuptools`! The idea behind standardizing this stuff is that projects *don’t* use setuptools by convention anymore but are able to use whatever they want.

Since setuptools is pretty slow and has a lot of lagacy features that few people need, many pure-python projects benefit from switching to a faster build backend.

But of course setuptools works fine, so no need to change anything if it works for you.

**Comment by mcmtroffaes** [comment]
Thanks @flying-sheep - I am thankful that you are looking out for the project. I find it super exciting how Python is modularizing/standardizing its packaging eco-system.

It's funny how pip agreed to build the package without a build-system specified... whence how this went under my radar.

**Comment by flying-sheep** [comment]
The default is

```toml
[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta:__legacy__'
```

which behaves as closely as possible like doing `python setup.py sdist bdist_wheel`.

But explicitly selecting a non-legacy backend works for almost all packages and executes much less hacky code.

**Pull request merged**
