### PR TITLE
Fix unicode errors

### PR DESCRIPTION
**Pull request by ghisvail**
Some tests fail to run on the Debian builders due to the default system encoding being set to ASCII instead of UTF-8. This commit explicitly set the encoding of all open streams to unicode, which make the tests pass.

### CODE REVIEW

**Comment by mcmtroffaes** [comment]
Thanks. I'll fix the other regression errors first. Maybe there should be an ASCII locale test on travis too.

**Comment by mcmtroffaes** [comment]
Merged (with additional fixes and travis test) here: https://github.com/mcmtroffaes/sphinxcontrib-bibtex/pull/123 Thanks again!

**Comment by ghisvail** [comment]
Could you tag and upload a new release with the latest fixes please?

**Comment by mcmtroffaes** [comment]
Done. Thanks again for your help with this release!

**Pull request closed without merging**
