### PR TITLE
Fix KeyError on empty footbibliography

### PR DESCRIPTION
**Pull request by mcmtroffaes**
See issue #223.

### CODE REVIEW

**Comment by mcmtroffaes** [comment]
@drammock Could you check if this branch fixes your problem?

**Comment by drammock** [comment]
test is running here: https://github.com/mne-tools/mne-python/pull/8684

**Comment by mcmtroffaes** [comment]
Thanks for running it through your CI. If I'm reading the pull request checks right, it looks like this fixed it? I'll merge this now, and will prep another hotfix release tomorrow first thing in the morning.

**Comment by drammock** [comment]
yes, it appears to have worked.

**Pull request merged**
