### PR TITLE
Use SphinxPostTransform to avoid having to run sphinx twice.

### PR DESCRIPTION
**Pull request by mcmtroffaes**
Still work in progress but for now it looks like this will be working. Quite  few tests are failing, I'll be working through these and then hopefully some kind folks could help testing, because this is a pretty major overhaul.

Also see discussion at #214.

### CODE REVIEW

**Comment by mcmtroffaes** [comment]
@chrisjsewell @matthewfeickert @choldgraf @jedbrown @cpitclaudel This might still be a bit rough around the edges, but the full test suite is now passing. Mind giving this a spin in the next week or so, or even doing a code review if it is up your alley, its a big patch and more eyes would be appreciated (especially as I understood @cpitclaudel had the intention to also work on this)? This new design uses the resolve phase to generate the full citation information, and then generates the actual citation and citation reference nodes in a post transform, so everything works with just a single sphinx run.

And merry Christmas! :-)

**Comment by chrisjsewell** [comment]
Thanks @mcmtroffaes!
Merry Chrimbo 🎄

**Comment by choldgraf** [comment]
Very cool! I’ll give a shot at trying it out this weekend or next week, really exciting to see!

**Comment by jedbrown** [comment]
I dropped this in my `requirements.txt` and got a successful build. Thanks! I'll merge it to our project when you release.
```
git+https://github.com/mcmtroffaes/sphinxcontrib-bibtex.git@feature/posttransform
``

**Comment by mcmtroffaes** [comment]
@jedbrown Many thanks for trying it out and confirming this works for you.

If anyone does run into some issues, do let me know. I'm planning to merge in a few days if no serious problems turn up.

**Comment by choldgraf** [comment]
I built the jupyter book docs with this PR as well and it seemed to work nicely! I didn't test it super rigorously but in general it seemed 👍

**Comment by mcmtroffaes** [comment]
Thanks as well for giving it a test run, @choldgraf.

I think this is now ready to go gold. The main missing part since my last status update was the backref support, I've added that in again. I'll merge and release on Monday afternoon unless anything problematic still turns up.

**Comment by mcmtroffaes** [comment]
Found an issue with duplicate ids (actually this had been a problem all along, the new design just flagged it more explicitly), this has now been fixed.

**Comment by choldgraf** [comment]
wahoo! 🚀

**Comment by matthewfeickert** [comment]
> This might still be a bit rough around the edges, but the full test suite is now passing. Mind giving this a spin in the next week or so, or even doing a code review if it is up your alley, its a big patch and more eyes would be appreciated? This new design uses the resolve phase to generate the full citation information, and then generates the actual citation and citation reference nodes in a post transform, so everything works with just a single sphinx run.
> 
> And merry Christmas! :-)

Sorry to have missed this while I was on holiday @mcmtroffaes, but thank you **very much** for all of this nice work and being so responsive and considerate to people's requests. Along with everyone else I'm happy to report that this is working great. :rocket:  Thanks! :)

**Pull request merged**
