### PR TITLE
Add support for footnote style bibliographies.

### PR DESCRIPTION
**Pull request by mcmtroffaes**
This provides one way of addressing #184. Note: currently needs the development version of pybtex-docutils to be installed from github.

### CODE REVIEW

**Comment by drammock** [comment]
I had some trouble getting it to work, but it seems to be OK now.  I was dealing with a case where three different functions defined within the same `.py` file each had some `:footcite:`s and a `.. footbibliography::` in their docstrings, and one of the cites was repeated in two of the docstrings.  For a while I was hitting an error where it was thinking that the parent folder of the bibliography file was itself a bibliography file (see excerpt of traceback below):

```
checking for /opt/mne/python/doc/references.bib in bibtex cache... not foundckground                                                                                                                                                                                           
parsing bibtex file /opt/mne/python/doc/references.bib... parsed 146 entries
checking for /opt/mne/python/doc/references.bib in bibtex cache... up to datection_ssp                                                                                                                                                                                         
checking for /opt/mne/python/doc/references.bib in bibtex cache... up to dateing_sss                                                                                                                                                                                           
checking for /opt/mne/python/doc/references.bib in bibtex cache... up to date                                                                                                                                                                                                  
checking for /opt/mne/python/doc/references.bib in bibtex cache... up to date                                                                                                                                                                                                  
checking for /opt/mne/python/doc/references.bib in bibtex cache... up to date                                                                                                                                                                                                  
checking for /opt/mne/python/doc/references.bib in bibtex cache... up to date                                                                                                                                                                                                  
checking for /opt/mne/python/doc/references.bib in bibtex cache... up to date                                                                                                                                                                                                  
checking for /opt/mne/python/doc/references.bib in bibtex cache... up to date                                                                                                                                                                                                  
checking for /opt/mne/python/doc in bibtex cache... not found
parsing bibtex file /opt/mne/python/doc... 
Traceback (most recent call last):
  File "/opt/sphinxcontrib-bibtex/sphinxcontrib/bibtex/cache.py", line 413, in process_bibfile
    bibfile_cache = cache[bibfile]
KeyError: '/opt/mne/python/doc'
```

But after trying various things I was able to get a full doc build to succeed. I'm not certain, but I think what eventually worked was doing a full build after removing one of the `.. footbibliography::` in a docstring that had the duplicate `:footcite:` (which yielded a `Unknown target name` warning), then putting the `.. footbibliography::` back in and rebuilding the docs.  Is there a particular cache file created by `sphinxcontrib.footbib` that I should add to our `make clean` recipe to make sure there aren't cache files hanging around that make things like this harder to debug?

**Comment by mcmtroffaes** [comment]
It's a strange bug that you hit there. No idea... There's nothing beyond the usual environment cache that is stored by sphinx internally. One thing I probably should do is version the cache data so that updates are less likely to break a build.

I don't think you're hitting this, but something to be aware of: with the current design, there should be only one footbibliography directive per document, and obviously it should come after all footcites. Multiple footcites to the same bibliography key are fine, and should be handled perfectly. If it's not then that's a bug. If you put footbibliography in your docstrings, and multiple of such docstrings are included in the same sphinx document, then you're certain to get errors. I will try to lift that limitation by collecting the current list of citations, and ensuring that footbibliography only includes the citations that occur above it (and following the previous footbibliography directive). That would be really neat, and cover more use cases.

If you don't mind, could you also test if parallel builds are working fine for your project (provided that you only use footbib)? This is a very new feature, whence.

**Comment by drammock** [comment]
Unfortunately we use a lot of extensions...  I tried switching to local cloned versions of all of them and hacking them to add `return {'parallel_read_safe': True}` to the `setup` functions in their `__init__` files, which seems to have worked for some of them, but `sphinx-bootstrap-theme` is still giving the "not declared if it is safe for parallel reading" warning even after that change.  So `sphinx-build` still does serial reads and I was unable to test parallel reads.

Interestingly, I did *not* have trouble with the case of one `.py` file in which several functions were defined, each function docstring with its own set of `:footcite:`s and its own `.. footbibliography::` directive (you seem to think this should have failed?)  For example, [this .py file](https://github.com/mne-tools/mne-python/pull/6931/files#diff-43c8a344892045c543bc80cdf0d32b3d) is just such a case; there are links in [this comment](https://github.com/mne-tools/mne-python/pull/6931#issuecomment-540843995) to the resulting API documentation pages as rendered by CircleCI.

**Comment by mcmtroffaes** [comment]
Ok, thanks for giving parallel building a try anyway.

Multiple footnote directives in the same *restructured text* document (wherever they come from, be it python docstrings, or anything else), will lead to issues as some footnotes will get redefined, so I don't recommend doing that for now. I'll try to have that fixed prior to release.

**Comment by drammock** [comment]
ahh, that makes sense.  For us each function / class gets made into its own `.rst` file so we wouldn't hit that limitation.  FWIW, I don't think our project requires the fix allowing multiple `footbibliography` directives in a single `.rst` document. But conceivably we might make use of it if it were possible, e.g., for a structured or annotated bibliography that grouped references thematically.

**Comment by kratsg** [comment]
Hi, [we're](https://github.com/scikit-hep/pyhf) interested in this solution as we tried something like

page1.rst
```
.. include: zbibliography.rst
```

page2.rst
```
.. include: zbibliography.rst
```

but this gives us both duplicate keys/labels warnings. when will there be a release with bibtex2?

**Comment by psanan** [comment]
Just wanted to add my +1 for looking forward to this feature in a release. I'm working on some new docs for [PETSc](https://gitlab.com/petsc/petsc) and this would be very helpful.

**Pull request merged**
