### PR TITLE
improved citation cache to fix unresolved citations issue

### PR DESCRIPTION
**Pull request by mcmtroffaes**

### CODE REVIEW

**Comment by mcmtroffaes** [comment]
@dizcza Would you mind testing this? This is a more invasive approach to fixing the citation ordering issues. It stores citation keys per document in an external ``bibtex.json`` file, thereby removing the requirement of needing documents to be ordered, at the expense of having to run the sphinx build twice whenever citations change (to generate the file).

**Comment by dizcza** [comment]
No citations are shown again. Lots of warnings that a citation is not found. In the end, a message that I need to rerun make command. I did. No citations.
If a user needs to run sphinx-build command manually twice, then I discourage such a solution - RTD simply won't get built.

**Comment by mcmtroffaes** [comment]
Thanks for trying it out. Indeed, the first run just collects the citations into a json file and does not attempt to resolve anything. Once the bibtex.json file is generated, all subsequent builds will correctly resolve citations. Can you try running ``sphinx-build`` as usual first, then ``sphinx-build -E`` on the second run (just in case, to force a fresh environment)? All subsequent runs (without the ``-E`` flag) will then work as normal. If you prefer to use the Makefile, first do ``make``, then ``make clean``, then ``make`` again.

This will work fine with RTD, or any other service, provided bibtex.json is stored in your version control.

**Comment by dizcza** [comment]
> If you prefer to use the Makefile, first do make, then make clean, then make again.

Even if it works, I better stick to `_toctree` than having this in mind.
Thanks for trying though.

**Comment by mcmtroffaes** [comment]
Sure, that's up to you. I've now removed the need to rebuild with a fresh environment. This should be fairly ready for merging now.

**Comment by dizcza** [comment]
With the latest commit, I still get a warning that I need to run the build command twice when I add a new bibtex reference after I clean up.
As you wish, I can always fix the version.

**Pull request merged**
